Rename 'master' to 'stable' and 'develop' to 'master'

diff --git a/git-hf-hotfix b/git-hf-hotfix
--- a/git-hf-hotfix
+++ b/git-hf-hotfix
@@ -92,8 +92,8 @@ cmd_list() {
 	local branch
 	for branch in $short_names; do
 		local fullname=$PREFIX$branch
-		local base=$(git merge-base "$fullname" "$MASTER_BRANCH")
-		local master_sha=$(git rev-parse "$MASTER_BRANCH")
+		local base=$(git merge-base "$fullname" "$STABLE_BRANCH")
+		local stable_sha=$(git rev-parse "$STABLE_BRANCH")
 		local branch_sha=$(git rev-parse "$fullname")
 		if [ "$fullname" = "$current_branch" ]; then
 			printf "* "
@@ -102,7 +102,7 @@ cmd_list() {
 		fi
 		if flag verbose; then
 			printf "%-${width}s" "$branch"
-			if [ "$branch_sha" = "$master_sha" ]; then
+			if [ "$branch_sha" = "$stable_sha" ]; then
 				printf "(no commits yet)"
 			else
 				local tagname=$(git name-rev --tags --no-undefined --name-only "$base")
@@ -161,11 +161,11 @@ require_version_arg() {
 	fi
 }
 
-require_base_is_on_master() {
+require_base_is_on_stable() {
 	if ! git branch --no-color --contains "$BASE" 2>/dev/null \
 			| sed 's/[* ] //g' \
-	  		| grep -q "^$MASTER_BRANCH\$"; then
-		die "fatal: Given base '$BASE' is not a valid commit on '$MASTER_BRANCH'."
+	  		| grep -q "^$STABLE_BRANCH\$"; then
+		die "fatal: Given base '$BASE' is not a valid commit on '$STABLE_BRANCH'."
 	fi
 }
 
@@ -192,7 +192,7 @@ use_current_hotfix_branch_name() {
 cmd_start() {
 	DEFINE_boolean fetch true "fetch from $ORIGIN before creating the new branch" F
 	parse_args "$@"
-	BASE=${2:-$MASTER_BRANCH}
+	BASE=${2:-$STABLE_BRANCH}
 	require_version_arg
 
 	# sanity checks
@@ -201,12 +201,12 @@ cmd_start() {
 	if flag fetch ; then
 		hubflow_fetch_latest_changes_from_origin
 	fi
-	require_base_is_on_master
+	require_base_is_on_stable
 	require_no_existing_hotfix_branches
 	require_branch_absent "$BRANCH"
 	require_tag_absent "$VERSION_PREFIX$VERSION"
-	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+	if has "$ORIGIN/$STABLE_BRANCH" $(git_remote_branches); then
+		require_branches_equal "$STABLE_BRANCH" "$ORIGIN/$STABLE_BRANCH"
 	fi
 
 	# create branch
@@ -238,7 +238,7 @@ cmd_finish() {
 	DEFINE_boolean push true "push to $ORIGIN after performing finish" p
 	DEFINE_boolean keep false "keep branch after performing finish" k
 	DEFINE_boolean notag false "don't tag this release" n
-	DEFINE_boolean nobackmerge false "don't back-merge $MASTER_BRANCH to be a parent of $DEVELOP_BRANCH (using tag if applicable)" b	parse_args "$@"
+	DEFINE_boolean nobackmerge false "don't back-merge $STABLE_BRANCH to be a parent of $MASTER_BRANCH (using tag if applicable)" b	parse_args "$@"
 	parse_args "$@"
 	require_version_arg
 
@@ -259,19 +259,19 @@ cmd_finish() {
 	fi
 
 	# we must be up to date before continuing
+	if has "$ORIGIN/$STABLE_BRANCH" $(git_remote_branches); then
+		require_branches_equal "$STABLE_BRANCH" "$ORIGIN/$STABLE_BRANCH"
+	fi
 	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
 	fi
-	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
-	fi
 
-	# try to merge into master
+	# try to merge into stable
 	# in case a previous attempt to finish this release branch has failed,
-	# but the merge into master was successful, we skip it now
-	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
-		git checkout "$MASTER_BRANCH" || \
-		  die "Could not check out $MASTER_BRANCH."
+	# but the merge into stable was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$STABLE_BRANCH"; then
+		git checkout "$STABLE_BRANCH" || \
+		  die "Could not check out $STABLE_BRANCH."
 		git merge --no-ff -srecursive -Xtheirs "$BRANCH" || \
 		  die "There were merge conflicts."
 		  # TODO: What do we do now?
@@ -292,31 +292,31 @@ cmd_finish() {
 		fi
 	fi
 
-	# try to merge into develop
+	# try to merge into master
 	if noflag nobackmerge; then
 		# in case a previous attempt to finish this hotfix branch has failed,
-		# but the merge into develop was successful, we skip it now
-		if ! git_is_branch_merged_into "$MASTER_BRANCH" "$DEVELOP_BRANCH"; then
-			git checkout "$DEVELOP_BRANCH" || \
-				die "Could not check out $DEVELOP_BRANCH."
-			# merge the master branch back into develop; this makes the master
-			# branch - and the new tag (if provided) - a parent of the development
+		# but the merge into master was successful, we skip it now
+		if ! git_is_branch_merged_into "$STABLE_BRANCH" "$MASTER_BRANCH"; then
+			git checkout "$MASTER_BRANCH" || \
+				die "Could not check out $MASTER_BRANCH."
+			# merge the stable branch back into master; this makes the stable
+			# branch - and the new tag (if provided) - a parent of the masterment
 			# branch, which in turn lets you use 'git describe' on either branch
 			if noflag notag; then
 				git merge --no-ff "$tagname" || \
 					die "There were merge conflicts."
 			else
-				git merge --no-ff "$MASTER_BRANCH" || \
+				git merge --no-ff "$STABLE_BRANCH" || \
 					die "There were merge conflicts."
 			fi
 		fi
 	else
 		# in case a previous attempt to finish this hotfix branch has failed,
-		# but the merge into develop was successful, we skip it now
-		if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
-			git checkout "$DEVELOP_BRANCH" || \
-				die "Could not check out $DEVELOP_BRANCH."
-			# just merge the release branch into the development branch
+		# but the merge into master was successful, we skip it now
+		if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
+			git checkout "$MASTER_BRANCH" || \
+				die "Could not check out $MASTER_BRANCH."
+			# just merge the release branch into the masterment branch
 			git merge --no-ff "$BRANCH" || \
 				die "There were merge conflicts."
 		fi
@@ -335,10 +335,10 @@ cmd_finish() {
 	fi
 
 	if flag push; then
-		git push "$ORIGIN" "$DEVELOP_BRANCH" || \
-			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
 		git push "$ORIGIN" "$MASTER_BRANCH" || \
 			die "Could not push to $MASTER_BRANCH from $ORIGIN."
+		git push "$ORIGIN" "$STABLE_BRANCH" || \
+			die "Could not push to $STABLE_BRANCH from $ORIGIN."
 		if noflag notag; then
 			git push --tags "$ORIGIN" || \
 				die "Could not push tags to $ORIGIN."
@@ -348,18 +348,18 @@ cmd_finish() {
 	echo
 	echo "Summary of actions:"
 	echo "- Latest objects have been fetched from '$ORIGIN'"
-	echo "- Hotfix branch has been merged into '$MASTER_BRANCH'"
+	echo "- Hotfix branch has been merged into '$STABLE_BRANCH'"
 	if noflag notag; then
 		echo "- The hotfix was tagged '$VERSION_PREFIX$VERSION'"
 	fi
-	echo "- Hotfix branch has been back-merged into '$DEVELOP_BRANCH'"
+	echo "- Hotfix branch has been back-merged into '$MASTER_BRANCH'"
 	if flag keep; then
 		echo "- Hotfix branch '$BRANCH' is still available"
 	else
 		echo "- Hotfix branch '$BRANCH' has been deleted"
 	fi
 	if flag push; then
-		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+		echo "- '$MASTER_BRANCH', '$STABLE_BRANCH' and tags have been pushed to '$ORIGIN'"
 	fi
 	echo
 }
@@ -370,7 +370,7 @@ cmd_cancel() {
 	DEFINE_boolean push true "push to $ORIGIN after performing cancel" p
 	DEFINE_boolean keep false "keep branch after performing cancel" k
 	DEFINE_boolean force false "safety feature; cannot cancel a hotfix without this flag" f
-	DEFINE_boolean discard true "drop the changes in this hotfix; do not merge back into develop" d
+	DEFINE_boolean discard true "drop the changes in this hotfix; do not merge back into master" d
 
 	parse_args "$@"
 	require_version_arg
@@ -389,32 +389,32 @@ cmd_cancel() {
 		git push "$ORIGIN" "$BRANCH" || die "Could not push hotfix branch up to $ORIGIN"
 	fi
 
-	# we only merge into develop if the user hasn't selected the -d flag
+	# we only merge into master if the user hasn't selected the -d flag
 	if noflag discard ; then
 		if flag fetch ; then
-			git fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
-			  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
+			git fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
+			  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
 		fi
-		if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
-			require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+		if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
+			require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
 		fi
 
-		# try to merge into develop
+		# try to merge into master
 		#
 		# in case a previous attempt to finish this release branch has failed,
-		# but the merge into develop was successful, we skip it now
-		if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
-			git checkout "$DEVELOP_BRANCH" || \
-				die "Could not check out $DEVELOP_BRANCH."
-			# just merge the release branch into the development branch
+		# but the merge into master was successful, we skip it now
+		if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
+			git checkout "$MASTER_BRANCH" || \
+				die "Could not check out $MASTER_BRANCH."
+			# just merge the release branch into the masterment branch
 			git merge --no-ff "$BRANCH" || \
 				die "There were merge conflicts."
 		fi
 
 		# push back to remote repo
 		if flag push ; then
-			git push "$ORIGIN" "$DEVELOP_BRANCH" || \
-				die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
+			git push "$ORIGIN" "$MASTER_BRANCH" || \
+				die "Could not push to $MASTER_BRANCH from $ORIGIN."
 		fi
 	fi
 
@@ -427,7 +427,7 @@ cmd_cancel() {
 	# delete local branch
 	if noflag keep ; then
 		if [ "$BRANCH" = "$(git_current_branch)" ]; then
-			git checkout "$DEVELOP_BRANCH"
+			git checkout "$MASTER_BRANCH"
 		fi
 
 		git branch -D "$BRANCH"
@@ -439,10 +439,10 @@ cmd_cancel() {
 		echo "- Latest objects have been fetched from '$ORIGIN'"
 	fi
 	if noflag discard ; then
-		echo "- Hotfix branch has been merged into '$DEVELOP_BRANCH'"
+		echo "- Hotfix branch has been merged into '$MASTER_BRANCH'"
 	fi
 	if noflag discard && flag push ; then
-		echo "- '$DEVELOP_BRANCH' has been pushed to '$ORIGIN'"
+		echo "- '$MASTER_BRANCH' has been pushed to '$ORIGIN'"
 	fi
 	if flag push ; then
 		echo "- Hotfix branch '$BRANCH' in '$ORIGIN' has been deleted."
diff --git a/hubflow-common b/hubflow-common
--- a/hubflow-common
+++ b/hubflow-common
@@ -174,14 +174,14 @@ git_is_branch_merged_into() {
 #
 
 # check if this repo has been inited for hubflow
+hubflow_has_stable_configured() {
+	local stable=$(git config --get hubflow.branch.stable)
+	[ "$stable" != "" ] && git_local_branch_exists "$stable"
+}
+
 hubflow_has_master_configured() {
 	local master=$(git config --get hubflow.branch.master)
 	[ "$master" != "" ] && git_local_branch_exists "$master"
-}
-
-hubflow_has_develop_configured() {
-	local develop=$(git config --get hubflow.branch.develop)
-	[ "$develop" != "" ] && git_local_branch_exists "$develop"
 }
 
 hubflow_has_prefixes_configured() {
@@ -193,18 +193,18 @@ hubflow_has_prefixes_configured() {
 }
 
 hubflow_is_initialized() {
-	hubflow_has_master_configured                    && \
-	hubflow_has_develop_configured                   && \
-	[ "$(git config --get hubflow.branch.master)" !=    \
-	  "$(git config --get hubflow.branch.develop)" ] && \
+	hubflow_has_stable_configured                    && \
+	hubflow_has_master_configured                   && \
+	[ "$(git config --get hubflow.branch.stable)" !=    \
+	  "$(git config --get hubflow.branch.master)" ] && \
 	hubflow_has_prefixes_configured
 }
 
 # loading settings that can be overridden using git config
 hubflow_load_settings() {
 	export DOT_GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
+	export STABLE_BRANCH=$(git config --get hubflow.branch.stable)
 	export MASTER_BRANCH=$(git config --get hubflow.branch.master)
-	export DEVELOP_BRANCH=$(git config --get hubflow.branch.develop)
 	export ORIGIN=$(git config --get hubflow.origin || echo origin)
     export BRANCH=$(git_current_branch)
 }
@@ -366,23 +366,23 @@ hubflow_merge_latest_changes_from_origin() {
     # remember which branch is currently checked out
     hubflow_branch_push_current_branch
 
-    # merge the master branch first
-    # merge conflicts on master will be rare
+    # merge the stable branch first
+    # merge conflicts on stable will be rare
+    if has "$ORIGIN/$STABLE_BRANCH" $(git_remote_branches); then
+        hubflow_remote_merge_helper "$ORIGIN" "$STABLE_BRANCH" no_checkout_afterwards
+        git_compare_branches "$STABLE_BRANCH" "$ORIGIN/$STABLE_BRANCH"
+        if [[ $? -ne 0 ]] ; then
+            git push "$ORIGIN" "$STABLE_BRANCH" || die "Push to '$ORIGIN' failed"
+        fi
+    fi
+
+    # merge the master branch next
+    # merge conflicts on master are sadly more common
     if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
         hubflow_remote_merge_helper "$ORIGIN" "$MASTER_BRANCH" no_checkout_afterwards
         git_compare_branches "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
         if [[ $? -ne 0 ]] ; then
             git push "$ORIGIN" "$MASTER_BRANCH" || die "Push to '$ORIGIN' failed"
-        fi
-    fi
-
-    # merge the develop branch next
-    # merge conflicts on develop are sadly more common
-    if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
-        hubflow_remote_merge_helper "$ORIGIN" "$DEVELOP_BRANCH" no_checkout_afterwards
-        git_compare_branches "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
-        if [[ $? -ne 0 ]] ; then
-            git push "$ORIGIN" "$DEVELOP_BRANCH" || die "Push to '$ORIGIN' failed"
         fi
     fi
 
